version: "3"

services:
    app:
        build:
            context: .
        container_name:
            sneaky-frontend
        ports:
            - "8080:8080"
        volumes:
            - ./app:/app 
        command: >
                sh -c "npm run serve"